version: "3.8"

services:
  web:
    build: .
    command: gunicorn intellifind.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
      - static_volume:/app/static
    depends_on:
      - db
    networks:
      - my_network
    environment:
      - DEBUG=False
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=3306
      - DJANGO_DB_NAME=my_database
      - DJANGO_DB_USER=root
      - DJANGO_DB_PASSWORD=my_password

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my_password
      MYSQL_DATABASE: my_database
    networks:
      - my_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/static
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - my_network

volumes:
  db_data:
  static_volume:

networks:
  my_network:
    driver: bridge
